# Generated by Django 5.2.3 on 2025-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("SAVE", "saved"), ("SPENT", "used")],
                        default="SAVE",
                        max_length=7,
                    ),
                ),
                ("price", models.FloatField()),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PKR", "Pakistan Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("CAD", "Canadian Dollar"),
                            ("SAR", "Saudi Riyal"),
                        ],
                        default="PKR",
                        max_length=3,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
